// Pure(ish) building blocks for the pre-build embed pipeline (design D1-D5).
import { createHash } from 'node:crypto';

const FLAG = 'BERLIN_WEB_UI';

const decodeEntities = (s) =>
  s
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&');

// D1: the flag lives only in JUCERPROJECT@defines; anywhere else is an error.
export function readWebUiFlag(jucerXml) {
  const tag = /<JUCERPROJECT\b[^>]*>/.exec(jucerXml);
  if (!tag) throw new Error('JUCERPROJECT element not found');
  const attr = /\sdefines="([^"]*)"/.exec(tag[0]);
  const rest = attr ? jucerXml.replace(attr[0], '') : jucerXml;
  if (rest.includes(FLAG)) throw new Error(`${FLAG} must only be set in JUCERPROJECT defines`);
  if (!attr) return false;

  for (const token of decodeEntities(attr[1]).split(/[\s,]+/)) {
    const [name, ...value] = token.split('=');
    if (name === FLAG) return value.length === 0 || value.join('=').trim() !== '0';
  }
  return false;
}

const hex = (buf) => Array.from(buf, (b) => `0x${b.toString(16).padStart(2, '0')}`).join(',');

// D2: stub = empty table, full = every asset. Output is deterministic.
export function renderAssetSources({ mode, assets }) {
  const full = mode === 'full';
  const header = [
    '// Generated by ui/scripts/embed-assets.mjs - do not edit.',
    '#pragma once',
    '#include "ui/WebAssets.h"',
    `#define BERLIN_EMBEDDED_ASSETS_FULL ${full ? 1 : 0}`,
    'namespace berlin { AssetTable getEmbeddedAssets(); }',
    '',
  ].join('\n');

  const sorted = full
    ? assets.map((a) => ({ path: a.path.replace(/\\/g, '/'), data: a.data })).sort((a, b) => (a.path < b.path ? -1 : 1))
    : [];

  const lines = ['// Generated by ui/scripts/embed-assets.mjs - do not edit.', '#include "EmbeddedAssets.h"', 'namespace berlin', '{'];
  sorted.forEach((a, i) => lines.push(`static const unsigned char asset${i}[] = { ${a.data.length ? hex(a.data) : '0x00'} };`));
  if (sorted.length === 0) {
    lines.push('AssetTable getEmbeddedAssets() { return { nullptr, 0 }; }');
  } else {
    lines.push('static const EmbeddedAsset entries[] = {');
    sorted.forEach((a, i) => lines.push(`    { ${JSON.stringify(a.path)}, asset${i}, ${a.data.length} },`));
    lines.push('};');
    lines.push(`AssetTable getEmbeddedAssets() { return { entries, ${sorted.length} }; }`);
  }
  lines.push('}', '');
  return { header, source: lines.join('\n') };
}

// D5: hash of the mode plus every listed input (path and bytes).
export function computeStamp(mode, inputs) {
  const h = createHash('sha256');
  h.update(`mode:${mode}\n`);
  for (const f of [...inputs].sort((a, b) => (a.path < b.path ? -1 : 1))) {
    h.update(`file:${f.path}:${f.data.length}\n`);
    h.update(f.data);
  }
  return h.digest('hex');
}

const notFound = () => Object.assign(new Error('BRL002: pnpm not found on PATH'), { code: 'BRL002' });

function runPnpm(spawn, args) {
  const r = spawn('pnpm', args);
  if (r.error) throw r.error.code === 'ENOENT' ? notFound() : r.error;
  return r.status;
}

// D3/D5: `io` and `spawn` are injected so the pipeline is testable without a disk or pnpm.
export function runPipeline({ flagOn, spawn, io }) {
  const mode = flagOn ? 'full' : 'stub';
  const stamp = computeStamp(mode, io.stampInputs());
  if (io.read('.stamp') === stamp && io.read('EmbeddedAssets.h') !== null && io.read('EmbeddedAssets.cpp') !== null) {
    return { skipped: true };
  }

  if (flagOn) {
    if (runPnpm(spawn, ['--version']) !== 0) throw notFound();
    if (runPnpm(spawn, ['--dir', 'ui', 'install', '--frozen-lockfile']) !== 0) throw new Error('BRL003: pnpm install failed');
    if (runPnpm(spawn, ['--dir', 'ui', 'run', 'build']) !== 0) throw new Error('BRL003: pnpm run build failed');
  }

  const { header, source } = renderAssetSources({ mode, assets: flagOn ? io.collectAssets() : [] });
  io.writeIfChanged('EmbeddedAssets.h', header);
  io.writeIfChanged('EmbeddedAssets.cpp', source);
  io.writeIfChanged('.stamp', stamp);
  return { skipped: false };
}
