// Pure(ish) building blocks for the pre-build embed pipeline (design D1-D5).
import { createHash } from 'node:crypto';

const FLAG = 'BERLIN_WEB_UI';

const decodeEntities = (s) =>
  s
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&');

// D1: the flag lives only in JUCERPROJECT@defines; anywhere else is an error.
export function readWebUiFlag(jucerXml) {
  const tag = /<JUCERPROJECT\b[^>]*>/.exec(jucerXml);
  if (!tag) throw new Error('JUCERPROJECT element not found');
  const attr = /\sdefines="([^"]*)"/.exec(tag[0]);
  const rest = attr ? jucerXml.replace(attr[0], '') : jucerXml;
  if (rest.includes(FLAG)) throw new Error(`${FLAG} must only be set in JUCERPROJECT defines`);
  if (!attr) return false;

  for (const token of decodeEntities(attr[1]).split(/[\s,]+/)) {
    const [name, ...value] = token.split('=');
    if (name === FLAG) return value.length === 0 || value.join('=').trim() !== '0';
  }
  return false;
}

const hex = (buf) => Array.from(buf, (b) => `0x${b.toString(16).padStart(2, '0')}`).join(',');

// D2: stub = empty table, full = every asset. Output is deterministic.
export function renderAssetSources({ mode, assets }) {
  const full = mode === 'full';
  const header = [
    '// Generated by ui/scripts/embed-assets.mjs - do not edit.',
    '#pragma once',
    '#include "ui/WebAssets.h"',
    '// 1 when the table holds the real UI build, 0 for the empty stub. WebEditor',
    '// static_asserts on it so a flag-on build can never ship the stub.',
    `#define BERLIN_EMBEDDED_ASSETS_FULL ${full ? 1 : 0}`,
    '',
  ].join('\n');

  const sorted = full
    ? assets.map((a) => ({ path: a.path.replace(/\\/g, '/'), data: a.data })).sort((a, b) => (a.path < b.path ? -1 : 1))
    : [];

  const lines = ['// Generated by ui/scripts/embed-assets.mjs - do not edit.', '#include "EmbeddedAssets.h"', 'namespace berlin', '{'];
  sorted.forEach((a, i) => lines.push(`static const unsigned char asset${i}[] = { ${a.data.length ? hex(a.data) : '0x00'} };`));
  if (sorted.length === 0) {
    lines.push('AssetTable getEmbeddedAssets() { return { nullptr, 0 }; }');
  } else {
    lines.push('static const EmbeddedAsset entries[] = {');
    sorted.forEach((a, i) => lines.push(`    { ${JSON.stringify(a.path)}, asset${i}, ${a.data.length} },`));
    lines.push('};');
    lines.push(`AssetTable getEmbeddedAssets() { return { entries, ${sorted.length} }; }`);
  }
  lines.push('}', '');
  return { header, source: lines.join('\n') };
}

// D5: hash of the mode plus every listed input (path and bytes).
export function computeStamp(mode, inputs) {
  const h = createHash('sha256');
  h.update(`mode:${mode}\n`);
  for (const f of [...inputs].sort((a, b) => (a.path < b.path ? -1 : 1))) {
    h.update(`file:${f.path}:${f.data.length}\n`);
    h.update(f.data);
  }
  return h.digest('hex');
}

const notFound = () => Object.assign(new Error('BRL002: pnpm not found on PATH'), { code: 'BRL002' });

// A hung pnpm must fail the build instead of hanging it. Must stay below LOCK_STALE_MS.
export const PNPM_TIMEOUT_MS = 5 * 60 * 1000;
export const LOCK_STALE_MS = 15 * 60 * 1000;
export const LOCK_TIMEOUT_MS = 20 * 60 * 1000;
const LOCK_POLL_MS = 200;
const RENAME_RETRIES = 10;
const RENAME_RETRY_MS = 50;

function runPnpm(spawn, args) {
  const r = spawn('pnpm', args, { timeout: PNPM_TIMEOUT_MS });
  if (r.error) {
    if (r.error.code === 'ENOENT') throw notFound();
    if (r.error.code === 'ETIMEDOUT') {
      throw new Error(`BRL006: pnpm ${args.join(' ')} timed out after ${PNPM_TIMEOUT_MS / 1000}s`);
    }
    throw r.error;
  }
  return r.status;
}

// The plugin pre-build runs once per project (SharedCode, VST3, ...) and they can overlap,
// all writing Source/ui/generated. Projucer has no per-target pre-build, so serialise here.
// `fs` is injected: create() -> true if the lock was created, mtimeMs() -> number|null,
// remove(), sleep(ms), now().
export function withLock(fs, fn, { staleMs = LOCK_STALE_MS, timeoutMs = LOCK_TIMEOUT_MS, pollMs = LOCK_POLL_MS } = {}) {
  const deadline = fs.now() + timeoutMs;
  for (;;) {
    if (fs.create()) {
      try {
        return fn();
      } finally {
        fs.remove();
      }
    }
    const mtime = fs.mtimeMs();
    if (mtime !== null && fs.now() - mtime > staleMs) {
      fs.remove();
      continue;
    }
    if (mtime !== null) {
      if (fs.now() > deadline) throw new Error('BRL005: timed out waiting for the generated-files lock');
      fs.sleep(pollMs);
    }
  }
}

// Windows can transiently deny/miss a rename while another process or AV holds the target.
export function renameWithRetry({ rename, sleep }, from, to, attempts = RENAME_RETRIES) {
  for (let i = 1; ; i++) {
    try {
      return rename(from, to);
    } catch (e) {
      if (!['EPERM', 'EBUSY', 'ENOENT'].includes(e.code) || i >= attempts) throw e;
      sleep(RENAME_RETRY_MS);
    }
  }
}

// D3/D5: `io` and `spawn` are injected so the pipeline is testable without a disk or pnpm.
// `io.withLock(fn)` is optional; when present the work (and a second stamp check) runs under it.
export function runPipeline({ flagOn, spawn, io }) {
  const mode = flagOn ? 'full' : 'stub';
  const upToDate = () => {
    const stamp = computeStamp(mode, io.stampInputs());
    const ok = io.read('.stamp') === stamp && io.read('EmbeddedAssets.h') !== null && io.read('EmbeddedAssets.cpp') !== null;
    return { ok, stamp };
  };

  if (upToDate().ok) return { skipped: true };

  const generate = () => {
    const { ok, stamp } = upToDate(); // a peer project may have finished while we waited
    if (ok) return { skipped: true };

    if (flagOn) {
      if (runPnpm(spawn, ['--version']) !== 0) throw notFound();
      if (runPnpm(spawn, ['--dir', 'ui', 'install', '--frozen-lockfile']) !== 0) throw new Error('BRL003: pnpm install failed');
      if (runPnpm(spawn, ['--dir', 'ui', 'run', 'build']) !== 0) throw new Error('BRL003: pnpm run build failed');
    }

    const { header, source } = renderAssetSources({ mode, assets: flagOn ? io.collectAssets() : [] });
    io.writeIfChanged('EmbeddedAssets.h', header);
    io.writeIfChanged('EmbeddedAssets.cpp', source);
    io.writeIfChanged('.stamp', stamp);
    return { skipped: false };
  };

  return io.withLock ? io.withLock(generate) : generate();
}
