/*
  ==============================================================================

   WebAssets - gui-free lookup of embedded web UI assets (webview-poc,
   embedded-ui-assets spec). juce_core only. The asset table itself is
   generated by ui/scripts/embed-assets.mjs (Source/ui/generated/).

  ==============================================================================
*/

#pragma once

#include <cstddef>
#include <optional>
#include <vector>

#include <juce_core/juce_core.h>

namespace berlin
{

struct EmbeddedAsset
{
    const char* path;
    const unsigned char* data;
    size_t size;
};

struct AssetTable
{
    const EmbeddedAsset* entries;
    size_t count;
};

struct AssetResource
{
    std::vector<std::byte> data;
    juce::String mimeType;
};

// "/" -> "index.html"; strips query/fragment and the leading "/".
// Rejects "..", "\", ":" and "%" (covers encoded traversal) with nullopt.
std::optional<juce::String> normaliseAssetPath (const juce::String& requestPath);

std::optional<AssetResource> findAsset (AssetTable table, const juce::String& requestPath);

// Case-insensitive extension lookup; falls back to application/octet-stream.
juce::String mimeTypeForPath (const juce::String& path);

// Defined by the generated Source/ui/generated/EmbeddedAssets.cpp.
AssetTable getEmbeddedAssets();

// appDataBase/Berlin/WebView2
juce::File webViewUserDataFolder (const juce::File& appDataBase);

} // namespace berlin
